apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
